name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Clean and Restore
      run: |
        dotnet clean CalculatorApp/CalculatorApp.csproj
        dotnet clean CalculatorApp.Tests.csproj
        dotnet restore CalculatorApp/CalculatorApp.csproj
        dotnet restore CalculatorApp.Tests.csproj

    - name: Build
      run: |
        dotnet build CalculatorApp/CalculatorApp.csproj --configuration Release --no-restore
        dotnet build CalculatorApp.Tests.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test CalculatorApp.Tests.csproj --configuration Release --no-restore
