name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Clean and Restore
      run: |
        dotnet clean CalculatorApp.sln
        dotnet restore CalculatorApp.sln

    - name: Build and Test
      run: |
        # Мы добавляем флаг -p:GenerateAssemblyInfo=false, чтобы убрать дубликаты
        dotnet build CalculatorApp.sln --no-restore -p:GenerateAssemblyInfo=false
        dotnet test CalculatorApp.sln --no-restore -p:GenerateAssemblyInfo=false
